Add error trap

diff --git a/.github/workflows/check-external-types.yml b/.github/workflows/check-external-types.yml
--- a/.github/workflows/check-external-types.yml
+++ b/.github/workflows/check-external-types.yml
@@ -41,6 +41,7 @@ jobs:
         run: |
           set -eEuo pipefail
           IFS=$'\n\t'
+          trap 's=$?; echo >&2 "$0: error on line "${LINENO}": ${BASH_COMMAND}"; exit ${s}' ERR
           metadata=$(cargo metadata --format-version=1 --no-deps)
           for id in $(jq <<<"${metadata}" '.workspace_members[]'); do
             pkg=$(jq <<<"${metadata}" ".packages[] | select(.id == ${id})")
@@ -70,6 +71,7 @@ jobs:
       - name: Run cargo check-external-types
         run: |
           set -eEuo pipefail
+          trap 's=$?; echo >&2 "$0: error on line "${LINENO}": ${BASH_COMMAND}"; exit ${s}' ERR
           # docs.rs uses -Z rustdoc-scrape-examples since https://github.com/rust-lang/docs.rs/pull/1954
           base_args=(${{ inputs.args }})
           IFS=$'\n\t'
diff --git a/.github/workflows/release-dry-run.yml b/.github/workflows/release-dry-run.yml
--- a/.github/workflows/release-dry-run.yml
+++ b/.github/workflows/release-dry-run.yml
@@ -44,6 +44,7 @@ jobs:
       - id: parse
         run: |
           set -eEuo pipefail
+          trap 's=$?; echo >&2 "$0: error on line "${LINENO}": ${BASH_COMMAND}"; exit ${s}' ERR
           workflow=$(yq '.' "${{ inputs.workflow }}")
           matrix=$(jq <<<"${workflow}" -c ".jobs.\"${{ inputs.job }}\".strategy.matrix")
           if [[ "${matrix}" == "null" ]]; then
diff --git a/.github/workflows/tidy.yml b/.github/workflows/tidy.yml
--- a/.github/workflows/tidy.yml
+++ b/.github/workflows/tidy.yml
@@ -62,6 +62,7 @@ jobs:
       - name: Run cargo clippy
         run: |
           set -eEuo pipefail
+          trap 's=$?; echo >&2 "$0: error on line "${LINENO}": ${BASH_COMMAND}"; exit ${s}' ERR
           args=(--workspace --all-targets ${{ inputs.args }})
           if [[ "${{ inputs.args }}" != *"-features"* ]]; then
             args+=(--all-features)
