Retry on rustup failure

diff --git a/.github/workflows/check-external-types.yml b/.github/workflows/check-external-types.yml
--- a/.github/workflows/check-external-types.yml
+++ b/.github/workflows/check-external-types.yml
@@ -53,8 +53,9 @@ jobs:
           if [[ -n "$(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [] and .targets[].kind[] == "lib")' <<<"${metadata}")" ]]; then
             printf 'has-lib=true\n' >>"${GITHUB_OUTPUT}"
           fi
-      - name: Install Rust
-        run: rustup toolchain add "${{ inputs.rust }}" --no-self-update --profile minimal && rustup default "${{ inputs.rust }}"
+      - uses: taiki-e/github-actions/install-rust@main
+        with:
+          toolchain: ${{ inputs.rust }}
         if: steps.pre.outputs.has-lib == 'true'
       - uses: taiki-e/cache-cargo-install-action@v2
         with:
@@ -68,6 +69,16 @@ jobs:
       - name: Run cargo check-external-types
         run: |
           trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
+          retry() {
+            for i in {1..10}; do
+              if "$@"; then
+                return 0
+              else
+                sleep "${i}"
+              fi
+            done
+            "$@"
+          }
           # docs.rs uses -Z rustdoc-scrape-examples since https://github.com/rust-lang/docs.rs/pull/1954
           # shellcheck disable=SC2206
           base_args=(${{ inputs.args }})
@@ -79,7 +90,7 @@ jobs:
           if [[ -n "${input_target}" ]]; then
             while read -rd,; do
               base_targets+=(--target="${REPLY}")
-              rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
+              retry rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
             done <<<"${input_target},"
           fi
           # Run cargo check-external-types for public crates with features specified in docs.rs metadata in Cargo.toml.
@@ -101,12 +112,12 @@ jobs:
               default_target=$(jq -r '."default-target"' <<<"${docs_rs_metadata}")
               if [[ "${default_target}" != null ]]; then
                 pkg_targets+=(--target="${default_target}")
-                rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
+                retry rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
               fi
               if [[ "$(jq '.targets' <<<"${docs_rs_metadata}")" != null ]]; then
                 for target in $(jq -r '.targets[]' <<<"${docs_rs_metadata}"); do
                   pkg_targets+=(--target="${target}")
-                  rustup target add "${target}" || true # tier 3 targets fail to install rustup target
+                  retry rustup target add "${target}" || true # tier 3 targets fail to install rustup target
                 done
               fi
             else
diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -44,8 +44,9 @@ jobs:
     timeout-minutes: 60
     steps:
       - uses: taiki-e/checkout-action@v1
-      - name: Install Rust
-        run: rustup toolchain add "${{ inputs.rust }}" --no-self-update --profile minimal && rustup default "${{ inputs.rust }}"
+      - uses: taiki-e/github-actions/install-rust@main
+        with:
+          toolchain: ${{ inputs.rust }}
       # Refs:
       # - https://github.com/rust-lang/docs.rs/blob/HEAD/crates/metadata/lib.rs
       # - https://github.com/rust-lang/docs.rs/blob/HEAD/src/docbuilder/rustwide_builder.rs
@@ -53,6 +54,16 @@ jobs:
       - name: Run cargo doc
         run: |
           trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
+          retry() {
+            for i in {1..10}; do
+              if "$@"; then
+                return 0
+              else
+                sleep "${i}"
+              fi
+            done
+            "$@"
+          }
           # docs.rs uses -Z rustdoc-scrape-examples since https://github.com/rust-lang/docs.rs/pull/1954
           # shellcheck disable=SC2206
           base_args=(
@@ -96,7 +107,7 @@ jobs:
           if [[ -n "${input_target}" ]]; then
             while read -rd,; do
               base_targets+=(--target="${REPLY}")
-              rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
+              retry rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
             done <<<"${input_target},"
           fi
           # Run cargo doc for public crates with features and rustc/rustdoc/cargo args specified in docs.rs metadata in Cargo.toml.
@@ -120,12 +131,12 @@ jobs:
                 default_target=$(jq -r '."default-target"' <<<"${docs_rs_metadata}")
                 if [[ "${default_target}" != null ]]; then
                   args+=(--target="${default_target}")
-                  rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
+                  retry rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
                 fi
                 if [[ "$(jq '.targets' <<<"${docs_rs_metadata}")" != null ]]; then
                   for target in $(jq -r '.targets[]' <<<"${docs_rs_metadata}"); do
                     args+=(--target="${target}")
-                    rustup target add "${target}" || true # tier 3 targets fail to install rustup target
+                    retry rustup target add "${target}" || true # tier 3 targets fail to install rustup target
                   done
                 fi
               else
diff --git a/.github/workflows/tidy.yml b/.github/workflows/tidy.yml
--- a/.github/workflows/tidy.yml
+++ b/.github/workflows/tidy.yml
@@ -53,15 +53,27 @@ jobs:
           if [[ -n "$(git ls-files '*.rs')" ]]; then
             printf 'rust=true\n' >>"${GITHUB_OUTPUT}"
           fi
-      - name: Install Rust
-        # TODO: do not install clippy if unneeded
-        run: rustup toolchain add "${{ inputs.rust }}" --no-self-update --profile minimal --component clippy,rustfmt && rustup default "${{ inputs.rust }}"
+      - uses: taiki-e/github-actions/install-rust@main
+        with:
+          toolchain: ${{ inputs.rust }}
+          # TODO: do not install clippy if unneeded
+          component: clippy,rustfmt
         if: steps.pre.outputs.rust == 'true'
       - uses: taiki-e/install-action@shellcheck
       - uses: taiki-e/install-action@shfmt
       - name: Run cargo clippy
         run: |
           trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
+          retry() {
+            for i in {1..10}; do
+              if "$@"; then
+                return 0
+              else
+                sleep "${i}"
+              fi
+            done
+            "$@"
+          }
           # shellcheck disable=SC2206
           args=(${{ inputs.args }})
           if [[ "${{ inputs.args }}" != *"-features"* ]]; then
@@ -74,7 +86,7 @@ jobs:
           if [[ -n "${input_target}" ]]; then
             while read -rd,; do
               args+=(--target="${REPLY}")
-              rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
+              retry rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
             done <<<"${input_target},"
           fi
           if [[ -n "${RUSTFLAGS:-}" ]]; then
