rust-release: Support uploading binaries

diff --git a/.github/workflows/release-dry-run.yml b/.github/workflows/release-dry-run.yml
--- a/.github/workflows/release-dry-run.yml
+++ b/.github/workflows/release-dry-run.yml
@@ -29,7 +29,7 @@ on:
       job:
         required: false
         type: string
-        default: upload-assets
+        default: release
 
 env:
   CARGO_INCREMENTAL: 0
@@ -65,82 +65,58 @@ jobs:
         run: |
           IFS=$'\n\t'
           trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
+          bail() {
+            printf '::error::%s\n' "$*"
+            exit 1
+          }
+          normalize_comma_or_space_separated() {
+            # Normalize whitespace characters into space because it's hard to handle single input contains lines with POSIX sed alone.
+            local list="${1//[$'\r\n\t']/ }"
+            if [[ "${list}" == *","* ]]; then
+              # If a comma is contained, consider it is a comma-separated list.
+              # Drop leading and trailing whitespaces in each element.
+              sed -E 's/ *, */,/g; s/^.//' <<<",${list},"
+            else
+              # Otherwise, consider it is a whitespace-separated list.
+              # Convert whitespace characters into comma.
+              sed -E 's/ +/,/g; s/^.//' <<<" ${list} "
+            fi
+          }
           job=$(pipx run yq -c ".jobs.\"${INPUT_JOB}\"" "${INPUT_WORKFLOW}")
-          matrix=$(jq -c '.strategy.matrix' <<<"${job}")
-          if [[ "${matrix}" == "null" ]]; then
-            printf '%s\n' "::error::'.jobs.${INPUT_JOB}.strategy.matrix' of ${INPUT_WORKFLOW} must set"
-            exit 1
+          bin=$(jq -r '.with."bin"' <<<"${job}")
+          bin_target=$(jq -r '.with."bin-target"' <<<"${job}")
+          if [[ "${bin}" == "null" ]]; then
+            bail "'.jobs.${INPUT_JOB}.with.bin' of ${INPUT_WORKFLOW} must set"
           fi
-          printf '%s\n' "matrix=${matrix}" >>"${GITHUB_OUTPUT}"
-          runs_on=$(jq -r '."runs-on"' <<<"${job}")
-          if [[ "${runs_on}" != '$'"{{ matrix.os }}" ]] && [[ "${runs_on}" != '$'"{{ matrix.os || 'ubuntu-latest' }}" ]]; then
-            printf '%s\n' "::error::'runs-on' must be "'$'"{{ matrix.os }} or "'$'"{{ matrix.os || 'ubuntu-latest' }}, but found ${runs_on}"
-            exit 1
+          if [[ "${bin_target}" == "null" ]]; then
+            bail "'.jobs.${INPUT_JOB}.with.bin-target' of ${INPUT_WORKFLOW} must set"
           fi
-          # Handle inputs for upload-rust-binary-action.
-          # https://github.com/taiki-e/upload-rust-binary-action/blob/HEAD/action.yml
-          for input in $(jq -c '.steps[] | select(.uses == "taiki-e/upload-rust-binary-action@v1") | .with | to_entries[]' <<<"${job}"); do
-            eval "$(jq -r '@sh "KEY=\(.key) value=\(.value)"' <<<"${input}")"
-            case "${KEY}" in
-              bin)
-                if [[ "${value}" == *'$'"{{"* ]]; then
-                  printf '%s\n' "::error::'"'$'"{{ .. }}' in 'bin' input option is not supported due to reusable workflow's limitation"
-                  exit 1
-                fi
-                printf '%s\n' "bin=${value}" >>"${GITHUB_OUTPUT}"
-                ;;
-              target)
-                if [[ "${value}" != "null" ]] && [[ "${value}" != '$'"{{ matrix.target }}" ]]; then
-                  printf '%s\n' "::error::'target' input option must be "'$'"{{ matrix.target }} or not set"
-                  exit 1
-                fi
-                ;;
-              build-tool)
-                if [[ "${value}" != "null" ]] && [[ "${value}" != '$'"{{ matrix.build-tool }}" ]]; then
-                  printf '%s\n' "::error::'build-tool' input option must be "'$'"{{ matrix.build-tool }} or not set"
-                  exit 1
-                fi
-                ;;
-              tar)
-                if [[ "${value}" == "null" ]]; then
-                  value=unix
-                elif [[ "${value}" == *'$'"{{"* ]]; then
-                  printf '%s\n' "::error::'"'$'"{{ .. }}' in 'tar' input option is not supported due to reusable workflow's limitation"
-                  exit 1
-                fi
-                printf '%s\n' "tar=${value}" >>"${GITHUB_OUTPUT}"
-                ;;
-              zip)
-                if [[ "${value}" == "null" ]]; then
-                  value=windows
-                elif [[ "${value}" == *'$'"{{"* ]]; then
-                  printf '%s\n' "::error::'"'$'"{{ .. }}' in 'zip' input option is not supported due to reusable workflow's limitation"
-                  exit 1
-                fi
-                printf '%s\n' "zip=${value}" >>"${GITHUB_OUTPUT}"
-                ;;
-              token | ref) ;;
-              *)
-                printf '%s\n' "::error::'${KEY}' input option is not supported yet by this reusable workflow"
-                exit 1
-                ;;
+          matrix=''
+          while read -rd, target; do
+            matrix+=',{"target":"'"${target}"'","os":"'
+            case "${target}" in
+              *-linux-gnu*) matrix+=ubuntu-22.04 ;;
+              *-apple-*) matrix+=macos-14 ;;
+              *-windows-*) matrix+=windows-2022 ;;
+              *) matrix+=ubuntu-latest ;;
             esac
-          done
+            matrix+='"}'
+          done < <(normalize_comma_or_space_separated "${bin_target}")
+          printf '%s\n' "matrix={\"include\":[${matrix#,}]}" >>"${GITHUB_OUTPUT}"
+          printf '%s\n' "bin=${bin}" >>"${GITHUB_OUTPUT}"
         env:
           INPUT_JOB: ${{ inputs.job }}
           INPUT_WORKFLOW: ${{ inputs.workflow }}
     outputs:
       matrix: ${{ steps.prepare.outputs.matrix }}
       bin: ${{ steps.prepare.outputs.bin }}
-      tar: ${{ steps.prepare.outputs.tar }}
-      zip: ${{ steps.prepare.outputs.zip }}
 
   build:
     needs: prepare
     strategy:
       fail-fast: false
       matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
-    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
+    runs-on: ${{ matrix.os }}
     timeout-minutes: 60
     steps:
       - uses: taiki-e/checkout-action@v1
@@ -151,7 +127,6 @@ jobs:
         with:
           target: ${{ matrix.target }}
           runner: none
-        if: matrix.build-tool != 'cross' && matrix.build-tool != 'cargo-zigbuild'
       - run: printf '%s\n' "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >>"${GITHUB_ENV}"
         if: contains(matrix.target, '-windows-msvc')
       - run: printf '%s\n' "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static -C link-self-contained=yes" >>"${GITHUB_ENV}"
@@ -161,34 +136,18 @@ jobs:
         if: matrix.target == 'x86_64-apple-darwin'
       - run: printf 'MACOSX_DEPLOYMENT_TARGET=11.0\n' >>"${GITHUB_ENV}"
         if: matrix.target == 'aarch64-apple-darwin' || matrix.target == 'universal-apple-darwin'
-      - uses: taiki-e/upload-rust-binary-action@v1
+      - id: build
+        uses: taiki-e/upload-rust-binary-action@v1
         with:
           dry-run: true
           bin: ${{ needs.prepare.outputs.bin }}
           target: ${{ matrix.target }}
-          build-tool: ${{ matrix.build-tool }}
-          tar: ${{ needs.prepare.outputs.tar }}
-          zip: ${{ needs.prepare.outputs.zip }}
+          tar: all
+          zip: windows
           ref: refs/tags/dummy
           token: dummy
-      - name: Get target name for artifact
-        id: artifact-target
-        run: |
-          IFS=$'\n\t'
-          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
-          if [[ -z "${TARGET}" ]]; then
-            host=$(rustc -vV | grep -E '^host:' | cut -d' ' -f2)
-            printf '%s\n' "artifact-target=${host}" >>"${GITHUB_OUTPUT}"
-          elif [[ "${BUILD_TOOL}" == 'cargo-zigbuild' ]]; then
-            printf '%s\n' "artifact-target=${TARGET%%.*}" >>"${GITHUB_OUTPUT}"
-          else
-            printf '%s\n' "artifact-target=${TARGET}" >>"${GITHUB_OUTPUT}"
-          fi
-        env:
-          TARGET: ${{ matrix.target }}
-          BUILD_TOOL: ${{ matrix.build-tool }}
       # For debugging
       - uses: actions/upload-artifact@v7
         with:
-          name: ${{ steps.artifact-target.outputs.artifact-target }}
-          path: ${{ needs.prepare.outputs.bin }}-${{ steps.artifact-target.outputs.artifact-target }}.*
+          name: ${{ matrix.target }}
+          path: ${{ steps.build.outputs.archive }}.*
diff --git a/.github/workflows/rust-release.yml b/.github/workflows/rust-release.yml
--- a/.github/workflows/rust-release.yml
+++ b/.github/workflows/rust-release.yml
@@ -1,4 +1,4 @@
-# Create and push the release commit and tag, create GitHub release, and publish crates.
+# Create and push the release commit and tag, publish crates, create GitHub release, and optionally upload binaries.
 #
 # There is no stability guarantee for this workflow, since it's supposed to only be
 # used in infra managed by us.
@@ -71,6 +71,7 @@
 #     permissions:
 #       contents: write # for taiki-e/create-gh-release-action
 #       id-token: write # for rust-lang/crates-io-auth-action
+#       attestations: write # unused (used when options for uploading binaries are set)
 #     secrets: inherit
 #     with:
 #       version: ${{ inputs.version }}
@@ -93,9 +94,39 @@
 #     permissions:
 #       contents: write # for taiki-e/create-gh-release-action
 #       id-token: write # for rust-lang/crates-io-auth-action
+#       attestations: write # unused (used when options for uploading binaries are set)
 #     secrets: inherit
 #     with:
 #       version: ${{ inputs.version }}
+# ```
+#
+# To upload binaries, you also need to set bin and bin-target:
+#
+# ```yaml
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       version:
+#         description: Version to be published
+#         required: true
+#         type: string
+#
+#   publish:
+#     if: github.repository_owner == '<owner>'
+#     uses: taiki-e/github-actions/.github/workflows/rust-release.yml@main
+#     permissions:
+#       contents: write # for taiki-e/create-gh-release-action / taiki-e/upload-rust-binary-action
+#       id-token: write # for rust-lang/crates-io-auth-action / actions/attest
+#       attestations: write # for actions/attest
+#     secrets: inherit
+#     with:
+#       version: ${{ inputs.version }}
+#       bin: <bin_name>
+#       bin-target: |
+#         x86_64-unknown-linux-gnu
+#         x86_64-unknown-linux-musl
+#         x86_64-apple-darwin
+#         x86_64-pc-windows-msvc
 # ```
 #
 # See "on.workflow_call.inputs" below for input options.
@@ -144,10 +175,12 @@ on:
       prefix:
         required: false
         type: string
-      draft:
+      bin:
         required: false
-        type: boolean
-        default: false
+        type: string
+      bin-target:
+        required: false
+        type: string
     outputs:
       ref:
         value: refs/tags/${{ jobs.prepare.outputs.tag }}
@@ -422,12 +455,34 @@ jobs:
 
           crates=$(normalize_comma_or_space_separated "${INPUT_CRATES}")
           printf '%s\n' "crates=${crates}" >>"${GITHUB_OUTPUT}"
+
+          if [[ -n "${BIN}" ]]; then
+            if [[ -z "${BIN_TARGET}" ]]; then
+              bail "'bin' input option may only be used together with 'bin-target' input option"
+            fi
+            matrix=''
+            while read -rd, target; do
+              matrix+=',{"target":"'"${target}"'","os":"'
+              case "${target}" in
+                *-linux-gnu*) matrix+=ubuntu-22.04 ;;
+                *-apple-*) matrix+=macos-14 ;;
+                *-windows-*) matrix+=windows-2022 ;;
+                *) matrix+=ubuntu-latest ;;
+              esac
+              matrix+='"}'
+            done < <(normalize_comma_or_space_separated "${BIN_TARGET}")
+            printf '%s\n' "matrix={\"include\":[${matrix#,}]}" >>"${GITHUB_OUTPUT}"
+          elif [[ -n "${BIN_TARGET}" ]]; then
+            bail "'bin-target' input option may only be used together with 'bin' input option"
+          fi
         env:
           VERSION: ${{ inputs.version }}
           TAG_PREFIX: ${{ inputs.tag-prefix }}
           CHANGELOG: ${{ inputs.changelog }}
           BRANCH: ${{ inputs.branch }}
           INPUT_CRATES: ${{ inputs.crates }}
+          BIN: ${{ inputs.bin }}
+          BIN_TARGET: ${{ inputs.bin-target }}
       - name: Build crates to be published
         run: |
           IFS=$'\n\t'
@@ -458,6 +513,7 @@ jobs:
       version: ${{ steps.check.outputs.version }}
       prev-version: ${{ steps.check.outputs.prev-version }}
       crates: ${{ steps.check.outputs.crates }}
+      matrix: ${{ steps.check.outputs.matrix }}
 
   release:
     needs: prepare
@@ -713,6 +769,92 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           TAG: ${{ needs.prepare.outputs.tag }}
-        if: (!inputs.draft)
+        if: inputs.bin == ''
     outputs:
       rev: ${{ steps.push.outputs.rev }}
+
+  upload-assets:
+    name: upload-assets ${{ matrix.target }}
+    if: inputs.bin != ''
+    needs: [prepare, release]
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 60
+    permissions:
+      contents: write # for taiki-e/upload-rust-binary-action
+      id-token: write # for actions/attest
+      attestations: write # for actions/attest
+    steps:
+      - uses: taiki-e/checkout-action@v1
+      # TODO: Use checkout-action's option once https://github.com/taiki-e/checkout-action/issues/3 implemented.
+      - run: |
+          IFS=$'\n\t'
+          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
+          retry() {
+            for i in {1..10}; do
+              if "$@"; then
+                return 0
+              else
+                sleep "${i}"
+              fi
+            done
+            "$@"
+          }
+          bail() {
+            printf '::error::%s\n' "$*"
+            exit 1
+          }
+          retry git fetch origin --tags &>/dev/null
+          git checkout "${REF}"
+          # Make sure the current revision is same as release step.
+          rev=$(git rev-parse HEAD)
+          if [[ "${rev}" != "${RELEASE_REV}" ]]; then
+            bail "revision difference between release step"
+          fi
+        env:
+          REF: refs/tags/${{ needs.prepare.outputs.tag }}
+          RELEASE_REV: ${{ needs.release.outputs.rev }}
+      - uses: taiki-e/github-actions/install-rust@main
+        with:
+          toolchain: ${{ inputs.rust }}
+      - uses: taiki-e/setup-cross-toolchain-action@v1
+        with:
+          target: ${{ matrix.target }}
+          runner: none
+      - run: printf '%s\n' "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >>"${GITHUB_ENV}"
+        if: contains(matrix.target, '-windows-msvc')
+      - run: printf '%s\n' "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static -C link-self-contained=yes" >>"${GITHUB_ENV}"
+        if: contains(matrix.target, '-linux-musl')
+      # https://doc.rust-lang.org/rustc/platform-support.html
+      - run: printf 'MACOSX_DEPLOYMENT_TARGET=10.12\n' >>"${GITHUB_ENV}"
+        if: matrix.target == 'x86_64-apple-darwin'
+      - run: printf 'MACOSX_DEPLOYMENT_TARGET=11.0\n' >>"${GITHUB_ENV}"
+        if: matrix.target == 'aarch64-apple-darwin' || matrix.target == 'universal-apple-darwin'
+      - id: upload
+        uses: taiki-e/upload-rust-binary-action@v1
+        with:
+          bin: ${{ inputs.bin }}
+          target: ${{ matrix.target }}
+          tar: all
+          zip: windows
+          ref: refs/tags/${{ needs.prepare.outputs.tag }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+      - uses: actions/attest@v4
+        with:
+          subject-path: ${{ steps.upload.outputs.archive }}.*
+
+  github-release:
+    if: inputs.bin != ''
+    needs: [prepare, release, upload-assets]
+    runs-on: ubuntu-slim
+    timeout-minutes: 15 # Max execution time of ubuntu-slim runner.
+    permissions:
+      contents: write # for gh release edit
+    steps:
+      - uses: taiki-e/checkout-action@v1
+      - run: gh release edit "${REF#refs/tags/}" --draft=false
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REF: refs/tags/${{ needs.prepare.outputs.tag }}
