Add "rust-" prefix to Rust-specific reusable workflows

diff --git a/.github/workflows/rust-docs.yml b/.github/workflows/rust-docs.yml
--- a/.github/workflows/rust-docs.yml
+++ b/.github/workflows/rust-docs.yml
@@ -1,4 +1,4 @@
-# Run `cargo check-external-types` in a way that respects the docs.rs metadata.
+# Run `cargo doc` in a way that is as similar to docs.rs as possible.
 #
 # There is no stability guarantee for this workflow, since it's supposed to only be
 # used in infra managed by us.
@@ -8,8 +8,8 @@
 # Usage:
 #
 # ```yaml
-#   check-external-types:
-#     uses: taiki-e/github-actions/.github/workflows/check-external-types.yml@main
+#   docs:
+#     uses: taiki-e/github-actions/.github/workflows/rust-docs.yml@main
 # ```
 #
 # See "on.workflow_call.inputs" below for input options.
@@ -22,7 +22,7 @@ on:
       rust:
         required: false
         type: string
-        default: nightly-2025-10-18
+        default: nightly
       target:
         required: false
         type: string
@@ -54,7 +54,7 @@ defaults:
     shell: bash --noprofile --norc -CeEuo pipefail {0}
 
 jobs:
-  check-external-types:
+  docs:
     runs-on: ubuntu-24.04
     timeout-minutes: 60
     steps:
@@ -63,15 +63,11 @@ jobs:
         with:
           tool: rust@${{ inputs.rust }}
           fallback: none
-      - uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
-        with:
-          tool: cargo-check-external-types@0.4.0
       # Refs:
       # - https://github.com/rust-lang/docs.rs/blob/HEAD/crates/metadata/lib.rs
       # - https://github.com/rust-lang/docs.rs/blob/HEAD/src/docbuilder/rustwide_builder.rs
-      # - https://github.com/awslabs/cargo-check-external-types
-      # NB: sync with docs.yml
-      - name: Run cargo check-external-types
+      # NB: sync with check-external-types.yml
+      - name: Run cargo rustdoc
         run: |
           IFS=$'\n\t'
           trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
@@ -98,25 +94,57 @@ jobs:
               sed -E 's/ +/,/g; s/^.//' <<<" ${list} "
             fi
           }
-          base_args=()
+          # docs.rs uses -Z rustdoc-scrape-examples since https://github.com/rust-lang/docs.rs/pull/1954
+          base_args=(
+            --lib
+            -Z unstable-options
+            -Z rustdoc-map
+            -Z rustdoc-scrape-examples
+            --config "doc.extern-map.registries.crates-io=\"https://docs.rs\""
+          )
           if [[ -n "${INPUT_ARGS}" ]]; then
             while IFS= read -rd' '; do
               [[ -z "${REPLY}" ]] || base_args+=("${REPLY}")
             done <<<"${INPUT_ARGS//[$'\r\n\t']/ } " # Normalize whitespace characters into space.
           fi
+          base_rustflags=()
+          base_rustdocflags=()
+          if [[ -n "${RUSTFLAGS:-}" ]]; then
+            while IFS= read -rd' '; do
+              [[ -z "${REPLY}" ]] || base_rustflags+=("${REPLY}")
+            done <<<"${RUSTFLAGS} "
+          fi
+          if [[ -n "${RUSTDOCFLAGS:-}" ]]; then
+            while IFS= read -rd' '; do
+              [[ -z "${REPLY}" ]] || base_rustdocflags+=("${REPLY}")
+            done <<<"${RUSTDOCFLAGS} "
+          fi
+          base_rustdocflags+=(
+            -Z unstable-options
+            # https://github.com/rust-lang/docs.rs/issues/2389
+            --cfg docsrs
+            --document-hidden-items
+            --document-private-items
+            --extern-html-root-takes-precedence
+          )
+          unset RUSTFLAGS
+          unset RUSTDOCFLAGS
+          export DOCS_RS=1
           metadata=$(cargo metadata --format-version=1 --no-deps)
           # Handle target inputs.
           base_targets=()
           if [[ -n "${INPUT_TARGET}" ]]; then
             while IFS= read -rd,; do
-              base_targets+=(--target="${REPLY}")
+              base_targets+=(--target "${REPLY}")
               retry rustup target add "${REPLY}" || true # tier 3 targets fail to install rustup target
             done < <(normalize_comma_or_space_separated "${INPUT_TARGET}")
           fi
-          # Run cargo check-external-types for public crates with features specified in docs.rs metadata in Cargo.toml.
+          # Run cargo rustdoc for public crates with features and rustc/rustdoc/cargo args specified in docs.rs metadata in Cargo.toml.
           # Publishing is unrestricted if null, and forbidden if an empty array.
-          for pkg in $(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [] and .targets[].kind[] == "lib")' <<<"${metadata}"); do
+          for pkg in $(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [])' <<<"${metadata}"); do
             args=("${base_args[@]}")
+            pkg_rustflags=("${base_rustflags[@]}")
+            pkg_rustdocflags=("${base_rustdocflags[@]}")
             eval "$(jq -r '@sh "MANIFEST_PATH=\(.manifest_path)"' <<<"${pkg}")"
             args+=(--manifest-path "${MANIFEST_PATH}")
             docs_rs_metadata=$(jq '.metadata.docs.rs' <<<"${pkg}")
@@ -126,22 +154,23 @@ jobs:
                 docs_rs_metadata='{}'
               fi
             fi
-            pkg_targets=()
-            # Respect target-related fields specified in docs.rs metadata if the input is empty.
-            if [[ -z "${INPUT_TARGET}" ]]; then
-              default_target=$(jq -r '."default-target"' <<<"${docs_rs_metadata}")
-              if [[ "${default_target}" != null ]]; then
-                pkg_targets+=(--target="${default_target}")
-                retry rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
+            if ! jq '.targets[] | .kind[]' <<<"${pkg}" | grep -Fq '"proc-macro"'; then
+              # Respect target-related fields specified in docs.rs metadata if the input is empty.
+              if [[ -z "${INPUT_TARGET}" ]]; then
+                default_target=$(jq -r '."default-target"' <<<"${docs_rs_metadata}")
+                if [[ "${default_target}" != null ]]; then
+                  args+=(--target "${default_target}")
+                  retry rustup target add "${default_target}" || true # tier 3 targets fail to install rustup target
+                fi
+                if [[ "$(jq '.targets' <<<"${docs_rs_metadata}")" != null ]]; then
+                  for target in $(jq -r '.targets[]' <<<"${docs_rs_metadata}"); do
+                    args+=(--target "${target}")
+                    retry rustup target add "${target}" || true # tier 3 targets fail to install rustup target
+                  done
+                fi
+              else
+                args+=("${base_targets[@]}")
               fi
-              if [[ "$(jq '.targets' <<<"${docs_rs_metadata}")" != null ]]; then
-                for target in $(jq -r '.targets[]' <<<"${docs_rs_metadata}"); do
-                  pkg_targets+=(--target="${target}")
-                  retry rustup target add "${target}" || true # tier 3 targets fail to install rustup target
-                done
-              fi
-            else
-              pkg_targets+=("${base_targets[@]}")
             fi
             if [[ "$(jq '.features' <<<"${docs_rs_metadata}")" != null ]]; then
               for feature in $(jq -r '.features[]' <<<"${docs_rs_metadata}"); do
@@ -154,24 +183,46 @@ jobs:
             if [[ "$(jq '."no-default-features"' <<<"${docs_rs_metadata}")" == 'true' ]]; then
               args+=(--no-default-features)
             fi
-            if [[ ${#pkg_targets[@]} -gt 0 ]]; then
-              # sort and dedup
-              IFS=$'\n'
-              # shellcheck disable=SC2207
-              pkg_targets=($(LC_ALL=C sort -u <<<"${pkg_targets[*]}"))
-              IFS=$'\n\t'
-              for target in "${pkg_targets[@]}"; do
-                (
-                  set -x
-                  cargo check-external-types "${args[@]}" "${target}"
-                )
+            if [[ "$(jq '."rustc-args"' <<<"${docs_rs_metadata}")" != null ]]; then
+              for arg in $(jq -r '."rustc-args"[]' <<<"${docs_rs_metadata}"); do
+                pkg_rustflags+=("${arg}")
               done
-            else
-              (
-                set -x
-                cargo check-external-types "${args[@]}"
+            fi
+            if [[ "$(jq '."rustdoc-args"' <<<"${docs_rs_metadata}")" != null ]]; then
+              for arg in $(jq -r '."rustdoc-args"[]' <<<"${docs_rs_metadata}"); do
+                pkg_rustdocflags+=("${arg}")
+              done
+            fi
+            if [[ -n "${pkg_rustflags[*]}" ]]; then
+              f=''
+              for flag in "${pkg_rustflags[@]}"; do
+                f+="\"${flag}\","
+              done
+              args+=(
+                --config "build.rustflags=[${f}]"
+                -Z host-config
+                -Z target-applies-to-host
+                --config "host.rustflags=[${f}]"
               )
             fi
+            if [[ -n "${pkg_rustdocflags[*]}" ]]; then
+              f=''
+              for flag in "${pkg_rustdocflags[@]}"; do
+                f+="\"${flag}\","
+              done
+              args+=(
+                --config "build.rustdocflags=[${f}]"
+              )
+            fi
+            if [[ "$(jq '."cargo-args"' <<<"${docs_rs_metadata}")" != null ]]; then
+              for arg in $(jq -r '."cargo-args"[]' <<<"${docs_rs_metadata}"); do
+                args+=("${arg}")
+              done
+            fi
+            (
+              set -x
+              cargo rustdoc "${args[@]}"
+            )
           done
         env:
           INPUT_ARGS: ${{ inputs.args }}
