tidy: Apply clippy to doctest

diff --git a/.github/workflows/tidy.yml b/.github/workflows/tidy.yml
--- a/.github/workflows/tidy.yml
+++ b/.github/workflows/tidy.yml
@@ -249,6 +249,10 @@ jobs:
             done
             "$@"
           }
+          bail() {
+            printf '::error::%s\n' "$*"
+            exit 1
+          }
           normalize_comma_or_space_separated() {
             # Normalize whitespace characters into space because it's hard to handle single input contains lines with POSIX sed alone.
             local list="${1//[$'\r\n\t']/ }"
@@ -272,7 +276,7 @@ jobs:
             done <<<"${INPUT_ARGS//[$'\r\n\t']/ } " # Normalize whitespace characters into space.
           fi
           host=$(rustc -vV | grep -E '^host:' | cut -d' ' -f2)
-          # metadata=$(cargo metadata --format-version=1 --no-deps)
+          metadata=$(cargo metadata --format-version=1 --no-deps)
           # Handle target inputs.
           run_host=''
           targets=()
@@ -331,18 +335,67 @@ jobs:
               )
             done
           fi
-          # TODO: [lints] table is not respected...
-          # # Refs:
-          # # - https://github.com/rust-lang/rust/issues/56232
-          # # - https://github.com/Nemo157/dotfiles/blob/cee1b90cb23089990fe9bc559b7c2f012d0a59f0/packages/cargo-rustdoc-clippy.sh
-          # export RUSTDOCFLAGS="${RUSTDOCFLAGS:-} -Z unstable-options --no-run --nocapture --test-builder clippy-driver"
-          # # filter bin-only crate due to https://github.com/rust-lang/cargo/issues/5477
-          # for manifest_path in $(jq -r '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and (.targets[].kind[] == "lib" or .targets[].kind[] == "proc-macro")) | .manifest_path' <<<"${metadata}"); do
-          #   (
-          #     set -x
-          #     cargo test --manifest-path "${manifest_path}" --doc "${args[@]}"
-          #   )
-          # done
+          # Refs:
+          # - https://github.com/rust-lang/rust/issues/56232
+          # - https://github.com/Nemo157/dotfiles/blob/cee1b90cb23089990fe9bc559b7c2f012d0a59f0/packages/cargo-rustdoc-clippy.sh
+          lints=$(pipx run --spec yq tomlq -c 'if .workspace then .workspace.lints else null end' Cargo.toml)
+          if [[ "${lints}" == 'null' ]]; then
+            lints='{}'
+          fi
+          clippy_args=(
+            -D warnings
+          )
+          while IFS='' read -r; do
+            [[ -n "${REPLY}" ]] || continue
+            if [[ "${REPLY}" == 'unexpected_cfgs' ]] || [[ "${REPLY}" == 'unexpected-cfgs' ]]; then
+              check_cfg="$(jq -c 'if (.rust."'"${REPLY}"'" | type == "object") then .rust."'"${REPLY}"'"."check-cfg" else null end' <<<"${lints}")"
+              if [[ "${check_cfg}" != 'null' ]] && [[ "${check_cfg}" != '[]' ]]; then
+                # TODO: check-cfg
+                clippy_args+=(-A "${REPLY}")
+                continue
+              fi
+            fi
+            clippy_args+=(-D "${REPLY}")
+          done <<<"$(jq -r 'if .rust then .rust | to_entries[] | select((.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | not) | .key else empty end' <<<"${lints}")"
+          while IFS='' read -r; do
+            [[ -n "${REPLY}" ]] || continue
+            clippy_args+=(-A "${REPLY}")
+          done <<<"$(jq -r 'if .rust then .rust | to_entries[] | select(.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | .key else empty end' <<<"${lints}")"
+          while IFS='' read -r; do
+            [[ -n "${REPLY}" ]] || continue
+            clippy_args+=(-D "clippy::${REPLY}")
+          done <<<"$(jq -r 'if .clippy then .clippy | to_entries[] | select((.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | not) | .key else empty end' <<<"${lints}")"
+          while IFS='' read -r; do
+            [[ -n "${REPLY}" ]] || continue
+            clippy_args+=(-A "clippy::${REPLY}")
+          done <<<"$(jq -r 'if .clippy then .clippy | to_entries[] | select(.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | .key else empty end' <<<"${lints}")"
+          # Lints emitted for code generated by rustdoc.
+          clippy_args+=(
+            -A clippy::semicolon_if_nothing_returned
+            -A clippy::used_underscore_items
+          )
+          IFS=' '
+          cat >/tmp/clippy-wrapper.sh <<EOF
+          #!/bin/sh
+          set -eu
+          clippy-driver ${clippy_args[*]} "\$@"
+          EOF
+          printf '%s\n' "+ cat -- /tmp/clippy-wrapper.sh"
+          cat -- /tmp/clippy-wrapper.sh
+          chmod +x /tmp/clippy-wrapper.sh
+          IFS=$'\n\t'
+          export RUSTDOCFLAGS="${RUSTDOCFLAGS:-} -Z unstable-options --no-run --test-builder /tmp/clippy-wrapper.sh"
+          printf '%s\n' "+ RUSTDOCFLAGS='${RUSTDOCFLAGS}' \\"
+          for manifest_path in $(jq -r '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .targets[].doctest == true) | .manifest_path' <<<"${metadata}"); do
+            use_workspace_lints=$(pipx run --spec yq tomlq -c 'if .lints and .lints.workspace then .lints.workspace else false end' "${manifest_path}")
+            if [[ "${use_workspace_lints}" != 'true' ]]; then
+              bail "'.lints.workspace = true must be set'"
+            fi
+            (
+              set -x
+              cargo test --manifest-path "${manifest_path}" --doc "${args[@]}" -- --nocapture
+            )
+          done
         env:
           INPUT_ARGS: ${{ inputs.clippy-args }}
           INPUT_TARGET: ${{ inputs.clippy-target }}
